name: Create GitHub release

# Create a GitHub release when a tag is pushed
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
          fetch-depth: 0

    - name: Generate latest changelog
      id: git-cliff
      uses: orhun/git-cliff-action@a9a95522b26fe6403f7bb24031f21fb573d0f5ff #v4.9.1
      with:
        config: cliff.toml
        args: --verbose --latest
      env:
        OUTPUT: CHANGELOG.md
        GITHUB_REPO: ${{ github.repository }}

    - name: Build Changelog URL and create release
      run: |
        TAG_NAME=${{ github.ref_name }}
        NOTES="${{ steps.git-cliff.outputs.changelog }}"
        gh release create "$TAG_NAME" --verify-tag --title "$TAG_NAME" --notes "$NOTES"


    - name: Generate full changelog
      uses: orhun/git-cliff-action@a9a95522b26fe6403f7bb24031f21fb573d0f5ff #v4.9.1
      with:
        config: cliff.toml
        args: --verbose
      env:
        OUTPUT: CHANGELOG.md
        GITHUB_REPO: ${{ github.repository }}

    - name: Package release notes
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: Changelog
        path: CHANGELOG.md