---
name: Tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  # Quick check so we don't waste minutes if there's a Flake8 error
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        ckan-version: ['2.12', '2.11', '2.10']
        experimental: [false]
        include:
          - ckan-version: 'master'
            experimental: true  # master is unstable, good to know if we are compatible or not

    name: ${{ matrix.experimental && '**Fail_Ignored** ' || '' }} Test on CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:${{ matrix.ckan-version }}
      options: --user root
    services:
      solr:
        image: ckan/ckan-solr:${{ matrix.ckan-version }}-solr9
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
      - uses: actions/checkout@v7.0.1
        timeout-minutes: 1
        continue-on-error: ${{ matrix.experimental }}

      - name: Install requirements
        # Install any extra requirements your extension has here (dev requirements, other extensions etc)
        run: |
          pip install -r requirements.txt -r dev-requirements.txt
          pip install -e .
        timeout-minutes: 10
        continue-on-error: ${{ matrix.experimental }}

      - name: Setup extension
        # Extra initialization steps
        run: |
          # Replace default path to CKAN core config file with the one on the container
          sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini
          ckan -c test.ini db init
        continue-on-error: ${{ matrix.experimental }}

      - name: Run tests
        run: pytest --ckan-ini=test.ini --cov=ckanext.oidc_pkce --disable-warnings ckanext/oidc_pkce --junit-xml=/tmp/artifacts/junit/results.xml
        continue-on-error: ${{ matrix.experimental }}

      - name: Test Summary
        uses: test-summary/action@v2.6
        continue-on-error: ${{ matrix.experimental }}
        with:
          paths: "/tmp/artifacts/junit/*.xml"
        if: always()
